export let bodypartdataList = new Promise((res, rej) =>
  res([
    "back",
    "cardio",
    "chest",
    "lower arms",
    "lower legs",
    "neck",
    "shoulders",
    "upper arms",
    "upper legs",
    "waist",
  ])
);
export let exercisesDataListValue = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/YxQaTbtL0E-nt8",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Place your hands behind your head with your elbows pointing outwards.",
      "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/cBSJNnRhFzWLtl",
    id: "0002",
    name: "45° side bend",
    target: "abs",
    secondaryMuscles: ["obliques"],
    instructions: [
      "Stand with your feet shoulder-width apart and your arms extended straight down by your sides.",
      "Keeping your back straight and your core engaged, slowly bend your torso to one side, lowering your hand towards your knee.",
      "Pause for a moment at the bottom, then slowly return to the starting position.",
      "Repeat on the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/Z-zwzq9mwvfKKB",
    id: "0003",
    name: "air bike",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Lie flat on your back with your hands placed behind your head.",
      "Lift your legs off the ground and bend your knees at a 90-degree angle.",
      "Bring your right elbow towards your left knee while simultaneously straightening your right leg.",
      "Return to the starting position and repeat the movement on the opposite side, bringing your left elbow towards your right knee while straightening your left leg.",
      "Continue alternating sides in a pedaling motion for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/sNgj-K8j-q9N8w",
    id: "0006",
    name: "alternate heel touchers",
    target: "abs",
    secondaryMuscles: ["obliques"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Extend your arms straight out to the sides, parallel to the ground.",
      "Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel.",
      "Return to the starting position and repeat on the left side, reaching your left hand towards your left heel.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "back",
    equipment: "cable",
    gifUrl: "https://v2.exercisedb.io/image/Jb9l6qxXq38qTQ",
    id: "0007",
    name: "alternate lateral pulldown",
    target: "lats",
    secondaryMuscles: ["biceps", "rhomboids"],
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/YKNhzkJOl1EqdL",
    id: "0009",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with your palms facing down and your arms fully extended.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Pause for a moment, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/YKNhzkJOl1EqdL",
    id: "0010",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with your palms facing down and your arms fully extended.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Pause for a moment, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/YKNhzkJOl1EqdL",
    id: "0011",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with your palms facing down and your arms fully extended.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Pause for a moment, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/YKNhzkJOl1EqdL",
    id: "0012",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Adjust the machine to your desired height and secure your knees on the pad.",
      "Grasp the handles with your palms facing down and your arms fully extended.",
      "Lower your body by bending your elbows until your upper arms are parallel to the floor.",
      "Pause for a moment, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/UASuaCwn3-6sRD",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/UASuaCwn3-6sRD",
    id: "0011",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/UASuaCwn3-6sRD",
    id: "0012",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/UASuaCwn3-6sRD",
    id: "0013",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/UUTnhQjJBR6Emw",
    id: "0014",
    name: "assisted hanging knee raise",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core muscles and lift your knees towards your chest, bending at the hips and knees.",
      "Pause for a moment at the top of the movement, squeezing your abs.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/cpd8mOfZVRJjuQ",
    id: "0015",
    name: "assisted lying leg raise with lateral throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "obliques"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your abs and lift your legs off the ground, keeping them straight.",
      "While keeping your legs together, lower them to one side until they are a few inches above the ground.",
      "Pause for a moment, then lift your legs back to the starting position.",
      "Repeat the movement to the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0016",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0017",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0018",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0019",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0018",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0019",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/fwtsmJHUItZvs1",
    id: "0020",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
];
export let exercisesDataList = new Promise((res, rej) =>
  res(exercisesDataListValue)
);
export let bodyPartBackData = new Promise((res, rej) =>
  res([
    {
      bodyPart: "back",
      equipment: "cable",
      gifUrl: "https://v2.exercisedb.io/image/bpGPMH4hXxp6W4",
      id: "0007",
      name: "alternate lateral pulldown",
      target: "lats",
      secondaryMuscles: ["biceps", "rhomboids"],
      instructions: [
        "Sit on the cable machine with your back straight and feet flat on the ground.",
        "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
        "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/0bCr0TwGAPxhS5",
      id: "0015",
      name: "assisted parallel close grip pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Adjust the machine to your desired weight and height.",
        "Place your hands on the parallel bars with a close grip, palms facing each other.",
        "Hang from the bars with your arms fully extended and your feet off the ground.",
        "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
        "Continue pulling until your chin is above the bars.",
        "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "leverage machine",
      gifUrl: "https://v2.exercisedb.io/image/GG6vozU0sqmfJ-",
      id: "0017",
      name: "assisted pull-up",
      target: "lats",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Adjust the machine to your desired weight and height settings.",
        "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
        "Hang with your arms fully extended and your feet off the ground.",
        "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
        "Continue pulling until your chin is above the handles.",
        "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/zzbt6gtKMst0BD",
      id: "0022",
      name: "barbell pullover to press",
      target: "lats",
      secondaryMuscles: ["triceps", "chest", "shoulders"],
      instructions: [
        "Lie flat on a bench with your head at one end and your feet on the ground.",
        "Hold the barbell with a pronated grip (palms facing away from you) and extend your arms straight above your chest.",
        "Keeping your arms straight, lower the barbell behind your head in an arc-like motion until you feel a stretch in your lats.",
        "Pause for a moment, then reverse the motion and press the barbell back to the starting position above your chest.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/KYtDY-tgxE76fX",
      id: "0027",
      name: "barbell bent over row",
      target: "upper back",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Stand with your feet shoulder-width apart and knees slightly bent.",
        "Bend forward at the hips while keeping your back straight and chest up.",
        "Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.",
        "Pull the barbell towards your lower chest by retracting your shoulder blades and squeezing your back muscles.",
        "Pause for a moment at the top, then slowly lower the barbell back to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/mWHZtDIbnrAur2",
      id: "0034",
      name: "barbell decline bent arm pullover",
      target: "lats",
      secondaryMuscles: ["triceps", "chest"],
      instructions: [
        "Lie down on a decline bench with your head lower than your hips and your feet secured.",
        "Hold a barbell with a pronated grip (palms facing away from you) and extend your arms straight above your chest.",
        "Lower the barbell behind your head in a controlled manner, keeping your arms slightly bent.",
        "Pause for a moment, then raise the barbell back to the starting position by contracting your lats.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/UVJkuQiH6iHHMU",
      id: "0037",
      name: "barbell decline wide-grip pullover",
      target: "lats",
      secondaryMuscles: ["triceps", "chest"],
      instructions: [
        "Lie on a decline bench with your head lower than your hips and your feet secured.",
        "Hold a barbell with a wide grip and extend your arms straight above your chest.",
        "Lower the barbell behind your head in a controlled manner, keeping your arms straight.",
        "Pause for a moment, then raise the barbell back to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/Y5uxlbpksAecCy",
      id: "0049",
      name: "barbell incline row",
      target: "upper back",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Set up an incline bench at a 45-degree angle.",
        "Lie face down on the bench with your chest against the pad and your feet flat on the ground.",
        "Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.",
        "Keep your back straight and your core engaged.",
        "Pull the barbell towards your chest, squeezing your shoulder blades together.",
        "Pause for a moment at the top, then slowly lower the barbell back to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/b6HDILwonjzRI-",
      id: "0064",
      name: "barbell one arm bent over row",
      target: "upper back",
      secondaryMuscles: ["biceps", "forearms"],
      instructions: [
        "Stand with your feet shoulder-width apart, knees slightly bent, and hold a barbell with one hand using an overhand grip.",
        "Bend forward at the hips, keeping your back straight and your head in a neutral position.",
        "Pull the barbell up towards your chest, keeping your elbow close to your body and squeezing your shoulder blades together.",
        "Lower the barbell back down to the starting position in a controlled manner.",
        "Repeat for the desired number of repetitions, then switch to the other arm.",
      ],
    },
    {
      bodyPart: "back",
      equipment: "barbell",
      gifUrl: "https://v2.exercisedb.io/image/nme3wBz6PgSZyb",
      id: "0073",
      name: "barbell pullover",
      target: "lats",
      secondaryMuscles: ["chest", "triceps"],
      instructions: [
        "Lie flat on a bench with your head at one end and your feet on the floor.",
        "Hold a barbell with a shoulder-width grip and extend your arms straight above your chest.",
        "Keeping your arms straight, lower the barbell behind your head in a controlled manner until you feel a stretch in your lats.",
        "Pause for a moment, then raise the barbell back to the starting position.",
        "Repeat for the desired number of repetitions.",
      ],
    },
  ])
);
export let bodyPartNeckData = new Promise((res, rej) =>
  res([
    {
      bodyPart: "neck",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/MksT7wFXpM4WyS",
      id: "0716",
      name: "side push neck stretch",
      target: "levator scapulae",
      secondaryMuscles: ["trapezius", "sternocleidomastoid"],
      instructions: [
        "Stand or sit up straight with your shoulders relaxed.",
        "Tilt your head to the right, bringing your right ear towards your right shoulder.",
        "Place your right hand on the left side of your head and gently apply pressure to increase the stretch.",
        "Hold the stretch for 15-30 seconds.",
        "Repeat on the other side, tilting your head to the left and applying pressure with your left hand.",
        "Repeat the stretch 2-3 times on each side.",
      ],
    },
    {
      bodyPart: "neck",
      equipment: "body weight",
      gifUrl: "https://v2.exercisedb.io/image/zWzaN5a96Ykjjc",
      id: "1403",
      name: "neck side stretch",
      target: "levator scapulae",
      secondaryMuscles: ["trapezius", "sternocleidomastoid"],
      instructions: [
        "Stand or sit up straight with your shoulders relaxed.",
        "Tilt your head to one side, bringing your ear towards your shoulder.",
        "Hold the stretch for 15-30 seconds.",
        "Repeat on the other side.",
        "Perform 2-4 sets on each side.",
      ],
    },
  ])
);
export let exerciseData = {
  bodyPart: "waist",
  equipment: "body weight",
  gifUrl: "https://v2.exercisedb.io/image/2hlHLDmzsA37mq",
  id: "0001",
  name: "3/4 sit-up",
  target: "abs",
  secondaryMuscles: ["hip flexors", "lower back"],
  instructions: [
    "Lie flat on your back with your knees bent and feet flat on the ground.",
    "Place your hands behind your head with your elbows pointing outwards.",
    "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.",
    "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
    "Repeat for the desired number of repetitions.",
  ],
};
export let youtubeVideoData = {
  contents: [
    {
      video: {
        channelId: "UCyj_-8VoHIuv04iEBsrKphQ",
        channelName: "Get Right Results",
        description:
          "This is a tutorial video on the proper performance of a Three Quarter (",
        lengthText: "0:44",
        publishedTimeText: "9 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/vvmcVK0CfHc/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAHDdV9tKKHCqDFNmXp_dkzg6RCWQ",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/vvmcVK0CfHc/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCWpHeQUwA2YbzAdoquoSaEdqJijw",
            width: 720,
          },
        ],
        title: "Tutorial | 3/4 Sit-Ups",
        videoId: "vvmcVK0CfHc",
        viewCountText: "1,794 views",
      },
    },
    {
      video: {
        channelId: "UCQfaOHrgP_QGU-E4Anx_4jA",
        channelName: "My PT Hub",
        description: "My PT Hub Fitness Exercises - ",
        lengthText: "0:16",
        publishedTimeText: "9 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/wm47Swzn_98/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBD8XFRhAzBJcasiDT-NsYRjEtsGg",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/wm47Swzn_98/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBlLchUCVPxHBszHV5FGVIUhDsKtQ",
            width: 720,
          },
        ],
        title: "3/4 Sit-Up",
        videoId: "wm47Swzn_98",
        viewCountText: "5,711 views",
      },
    },
    {
      video: {
        channelId: "UCQfaOHrgP_QGU-E4Anx_4jA",
        channelName: "My PT Hub",
        lengthText: "0:17",
        publishedTimeText: "8 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/qIyuxNyZ0NQ/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4Af4JgALQBYoCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLAz09lStY1d1VRM5LnPHex6n4w7ew",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/qIyuxNyZ0NQ/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLAXOH0uLj5p6XcLOomJB1ihSJ7YOw",
            width: 720,
          },
        ],
        title: "3:4 Sit Up",
        videoId: "qIyuxNyZ0NQ",
        viewCountText: "12,054 views",
      },
    },
    {
      video: {
        channelId: "UCZIIRX8rkNjVpP-oLMHpeDw",
        channelName: "Calisthenicmovement",
        description:
          "Our Workout Programs: ➡️ https://calimove.com ⬅️ ✔️Instagram ➢ https://instagram.com/calimove ✔️Facebook ...",
        lengthText: "6:52",
        publishedTimeText: "7 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/pIvDbMEdAxI/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLAVVeDFW12_zS2uQ9wt_DcJXqzUPg",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/pIvDbMEdAxI/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDX_62BsfNVqAcYWgN5PKt-QW4B9w",
            width: 720,
          },
        ],
        title: "3 Exercises Better Than Sit Ups",
        videoId: "pIvDbMEdAxI",
        viewCountText: "4,140,512 views",
      },
    },
    {
      video: {
        channelId: "UC65cPngDx5FG3qFZLexFwcA",
        channelName: "Gym visual",
        description: "3/4 Sit-up",
        lengthText: "0:07",
        publishedTimeText: "8 years ago",
        thumbnails: [
          {
            height: 270,
            url: "https://i.ytimg.com/vi/FXalPpHfkZk/hqdefault.jpg?sqp=-oaymwE9COADEI4CSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4AdQGgALgA4oCDAgAEAEYZSBlKGUwDw==&rs=AOn4CLCyu8bJm2BYLRIiSBzDdN7z4Av7Zw",
            width: 480,
          },
        ],
        title: "3/4 Sit-up",
        videoId: "FXalPpHfkZk",
        viewCountText: "6,480 views",
      },
    },
    {
      video: {
        channelId: "UCalHkG9WxYTbkrAahEVMzZw",
        channelName: "SàMy Ként",
        lengthText: "0:50",
        publishedTimeText: "11 years ago",
        thumbnails: [
          {
            height: 270,
            url: "https://i.ytimg.com/vi/nxFgeTpBP6s/hqdefault.jpg?sqp=-oaymwEjCOADEI4CSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBibjDQsj1uyNmfToW7oziac2oGgg",
            width: 480,
          },
        ],
        title: "3 4 Sit Up Exercise",
        videoId: "nxFgeTpBP6s",
        viewCountText: "2,392 views",
      },
    },
    {
      video: {
        channelId: "UCciJRT-2dBbecAA4e44CWRA",
        channelName: "FitSW Fitness Software",
        description:
          "Fitness Tracking Software for Personal Trainers. Keep fitness clients motivated with graphical fitness progress tracking & create ...",
        lengthText: "0:20",
        publishedTimeText: "7 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/pAMpwBOSTlQ/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLC0jqFdSed5lp1orB3q3izw6LAp2A",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/pAMpwBOSTlQ/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC4pueRO5Y63HNusKcRdTJApoSOGA",
            width: 720,
          },
        ],
        title: "3/4 Situp: Ab, Core Exercise Demo How-to",
        videoId: "pAMpwBOSTlQ",
        viewCountText: "6,384 views",
      },
    },
    {
      video: {
        channelId: "UCzepXKgbTZ6qi4HcO21itIQ",
        channelName: "Justin Agustin",
        description:
          "For Business Inquiries Email us at : info@justinagustin.com #shorts.",
        lengthText: "0:15",
        publishedTimeText: "3 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/wIUwcbUbatw/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AZQDgALQBYoCDAgAEAEYZSBcKFcwDw==&rs=AOn4CLDAy4xXsQY2aGxkJTPs56mk7BDVGw",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/wIUwcbUbatw/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AZQDgALQBYoCDAgAEAEYZSBcKFcwDw==&rs=AOn4CLAtpvCw6Ec0kX3gK9q6LiQHl5pTxA",
            width: 720,
          },
        ],
        title: "Sit Up Hacks for Beginners",
        videoId: "wIUwcbUbatw",
        viewCountText: "330,589 views",
      },
    },
    {
      video: {
        channelId: "UC4elGg3pun11d_SERi3g4vg",
        channelName: "Dr. Rob Jones",
        description: "No no no no no no no stop stop stop doing ",
        lengthText: "0:47",
        publishedTimeText: "1 year ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/Zc3lztqm4iQ/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AbYIgAKAD4oCDAgAEAEYTSBgKGUwDw==&rs=AOn4CLCpARZavPwtMewGZbbfVqH_7pSH1g",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/Zc3lztqm4iQ/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AbYIgAKAD4oCDAgAEAEYTSBgKGUwDw==&rs=AOn4CLBpEpeNxBuNx4LsNINNYF2vG_XyMQ",
            width: 720,
          },
        ],
        title: "Stop doing sit-ups ‼️ Do this to get abs instead ✅",
        videoId: "Zc3lztqm4iQ",
        viewCountText: "10,457,666 views",
      },
    },
    {
      video: {
        channelId: "UCNS8LDznQ2svWdVt0v-39XQ",
        channelName: "fitness school 009",
        description:
          "Here's a description you can use for a back muscles workout video or post: --- **Description:** Unlock the full potential of your ...",
        lengthText: "0:05",
        publishedTimeText: "2 days ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/MkIFwyfOkQc/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AcwFgAKACooCDAgAEAEYfyAzKCIwDw==&rs=AOn4CLBC2uSJOF0_oIZbfroXdjzDc7qK4w",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/MkIFwyfOkQc/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AcwFgAKACooCDAgAEAEYfyAzKCIwDw==&rs=AOn4CLAAzrNcgbo3bwLgrcAIxv2mLPh2bg",
            width: 720,
          },
        ],
        title:
          "Six pack workout at home #sixpack #viralshort #fitnessjourney  #exercise",
        videoId: "MkIFwyfOkQc",
        viewCountText: "6,224 views",
      },
    },
    {
      video: {
        channelId: "UCC82hSXrSxGlRoiY14R4g4w",
        channelName: "Cory Armstrong Fitness",
        description:
          "Apply To Work With Me 1 on 1 HERE: https://coryarmstrongfitness.com/coaching.",
        lengthText: "1:00",
        publishedTimeText: "1 year ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/IZITxlqZW_U/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4Ac4FgAKACooCDAgAEAEYZSBXKE0wDw==&rs=AOn4CLDqG7c7-KLR-cCHqO0_MHGgzCgwHQ",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/IZITxlqZW_U/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4Ac4FgAKACooCDAgAEAEYZSBXKE0wDw==&rs=AOn4CLDo0pg6TpWki2wdXYw1Vk0vgT-DZQ",
            width: 720,
          },
        ],
        title: "If You’re Doing Sit Ups to Lose Belly Fat- Do This Instead",
        videoId: "IZITxlqZW_U",
        viewCountText: "5,503,877 views",
      },
    },
    {
      video: {
        channelId: "UCE1u-C5RF6lMqevyLJSsE9Q",
        channelName: "Rhett Barber",
        lengthText: "0:13",
        publishedTimeText: "4 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/8DqEfCtHP-Y/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLDAVlFnm7aQ2k82Fcin1_C9pnvnOQ",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/8DqEfCtHP-Y/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCNFDLhV49Op9ahp4IcQBjmMFl1Ww",
            width: 720,
          },
        ],
        title: "3/4 sit ups",
        videoId: "8DqEfCtHP-Y",
        viewCountText: "243 views",
      },
    },
    {
      video: {
        channelId: "UCKvdn7rK5pXqUTzpEhhVsrA",
        channelName: "Yoga and Fitness with Shivali",
        description: "3/4 situp",
        lengthText: "0:38",
        publishedTimeText: "2 months ago",
        thumbnails: [
          {
            height: 270,
            url: "https://i.ytimg.com/vi/rcSeW-dEAmY/hqdefault.jpg?sqp=-oaymwE9COADEI4CSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4AbYEgALAAooCDAgAEAEYZyBnKGcwDw==&rs=AOn4CLB3ejatRy18jkGIYlOJNs2NSrXvYw",
            width: 480,
          },
        ],
        title: "How to do 3/4 sit up",
        videoId: "rcSeW-dEAmY",
        viewCountText: "65 views",
      },
    },
    {
      video: {
        channelId: "UCvZ6ZTyP-pE3rtqUAbGRYkQ",
        channelName: "Thomas Diggs",
        description:
          "Grab a mat and lay down flat on your back. Place your hands gently on your temples/chest and bend your knees so that you have ...",
        lengthText: "0:14",
        publishedTimeText: "2 weeks ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/EbwYx5gtYoo/hq720.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAElAADIQj0AgKJDeAHwAQH4Af4JgALQBYoCDAgAEAEYTyBlKEowDw==&rs=AOn4CLD7DUZVXiAXanuTkRfgGU8pfaquAA",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/EbwYx5gtYoo/hq720.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGAHwAQH4Af4JgALQBYoCDAgAEAEYTyBlKEowDw==&rs=AOn4CLAuIJLGrHPDAKVQ_7VURM4np5ofZA",
            width: 720,
          },
        ],
        title: "3/4 Sit-Ups",
        videoId: "EbwYx5gtYoo",
        viewCountText: "26 views",
      },
    },
    {
      video: {
        channelId: "UC4GJndVHEhdmqLFBHOCi97A",
        channelName: "Jordan Yeoh Fitness",
        description:
          "... your arms behind your neck you can even do like this or like this and it's not necessary to code all the way ",
        lengthText: "0:38",
        publishedTimeText: "1 year ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/eeJ_CYqSoT4/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AbYIgAKAD4oCDAgAEAEYZSBPKEAwDw==&rs=AOn4CLBjK1afjMdwUf5UZBETsDEI3c-H2w",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/eeJ_CYqSoT4/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBPKEAwDw==&rs=AOn4CLApRNcQjgAGOert27zAYiECk5TL4Q",
            width: 720,
          },
        ],
        title: "Crunches Tips  #abworkout #abs #sixpackabs  #fitness",
        videoId: "eeJ_CYqSoT4",
        viewCountText: "7,035,062 views",
      },
    },
    {
      video: {
        channelId: "UCh2w-xqEwSz96sbn2afbOVQ",
        channelName: "Redefining Strength",
        description: "How To Do A ",
        lengthText: "3:49",
        publishedTimeText: "4 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/NIANHU8d9m4/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBWn1Lm7bEw1Rq3wK9aNQhZFB91LA",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/NIANHU8d9m4/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDedYYbmBIN5p12EkxMdqFNmHFtVg",
            width: 720,
          },
        ],
        title: "How To Do A Sit Up Properly - 3 Tips To Help",
        videoId: "NIANHU8d9m4",
        viewCountText: "65,415 views",
      },
    },
    {
      video: {
        channelId: "UCKIoHDjPbJ1kQ3LVi0WcwgA",
        channelName: "FITTADDICT inc.",
        description:
          "Join us on Instagram for free workouts & giveaways! Try full training series for free at www.fittaddict.com ! -The Gun Show -The ...",
        lengthText: "0:22",
        publishedTimeText: "11 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/y_SSnkLy22w/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA3JrXpwhP0oXThZfpSu6cysgulHw",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/y_SSnkLy22w/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDfM7eBHAm0a5APy34uFHIjf7dqQw",
            width: 720,
          },
        ],
        title: "3 4 sit ups",
        videoId: "y_SSnkLy22w",
        viewCountText: "1,110 views",
      },
    },
    {
      video: {
        channelId: "UCSMWE3qNqigMoezmPASap8w",
        channelName: "Martin Rios",
        description:
          "In this video, Martin Rios looks at a pro boxer, Manny Pacquiao, who shares his insane ab workout routine of 3000 ",
        lengthText: "0:23",
        publishedTimeText: "1 year ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/zVcjldM1YMY/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4AbYIgAKAD4oCDAgAEAEYZSBNKE0wDw==&rs=AOn4CLAV4bRDno7T6vuZvEj5rVbK5jNNFw",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/zVcjldM1YMY/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4AbYIgAKAD4oCDAgAEAEYZSBNKE0wDw==&rs=AOn4CLA8sn537QoxkxzsIaP-N6fiWsj8rQ",
            width: 720,
          },
        ],
        title: "Pro Boxer's 3000 Sit Up Ab Workout 🤯🥊",
        videoId: "zVcjldM1YMY",
        viewCountText: "140,539 views",
      },
    },
    {
      video: {
        channelId: "UCwxklfO1LBHPdkcUkzY9duQ",
        channelName: "Live Lean TV",
        description:
          "Business Enquiries: info@LiveLeanTV.com How To Do Weighted ",
        lengthText: "0:11",
        publishedTimeText: "2 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/w3giolCm4fI/hq720_2.jpg?sqp=-oaymwE9COgCEMoBSFryq4qpAy8IARUAAAAAGAAlAADIQj0AgKJDeAHwAQH4Ac4FgAKACooCDAgAEAEYXCBcKFwwDw==&rs=AOn4CLDpAZmZUPhs8IsRPRbKqVsBzUmK9Q",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/w3giolCm4fI/hq720_2.jpg?sqp=-oaymwExCNAFEJQDSFryq4qpAyMIARUAAIhCGADwAQH4Ac4FgAKACooCDAgAEAEYXCBcKFwwDw==&rs=AOn4CLD_kZRfkPaIBHaLrh13ihs9inQL3g",
            width: 720,
          },
        ],
        title:
          "How To Do Weighted Sit Ups With Dumbbells (MUSCLES WORKED) | LiveLeanTV",
        videoId: "w3giolCm4fI",
        viewCountText: "24,167 views",
      },
    },
    {
      video: {
        channelId: "UCYXN30xkd-a0MXaQHbMsw0g",
        channelName: "Eternal Fitness",
        lengthText: "0:12",
        publishedTimeText: "5 years ago",
        thumbnails: [
          {
            height: 202,
            url: "https://i.ytimg.com/vi/qcL8me8Cah0/hq720.jpg?sqp=-oaymwEjCOgCEMoBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLBtXt0lEvdunfVfRYJNhEoR-BmH0w",
            width: 360,
          },
          {
            height: 404,
            url: "https://i.ytimg.com/vi/qcL8me8Cah0/hq720.jpg?sqp=-oaymwEXCNAFEJQDSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDl5PWijWEROVaQw04ksTidCq-xNA",
            width: 720,
          },
        ],
        title: "3/4 Sit Up",
        videoId: "qcL8me8Cah0",
        viewCountText: "17 views",
      },
    },
  ],
  estimatedResults: "3153811",
  next: "EqMDEgozLzQgc2l0LXVwGpQDU0JTQ0FRdDJkbTFqVmtzd1EyWklZNElCQzNkdE5EZFRkM3B1WHprNGdnRUxjVWw1ZFhoT2VWb3dUbEdDQVF0d1NYWkVZazFGWkVGNFNZSUJDMFpZWVd4UWNFaG1hMXByZ2dFTGJuaEdaMlZVY0VKUU5uT0NBUXR3UVUxd2QwSlBVMVJzVVlJQkMzZEpWWGRqWWxWaVlYUjNnZ0VMV21NemJIcDBjVzAwYVZHQ0FRdE5hMGxHZDNsbVQydFJZNElCQzBsYVNWUjRiSEZhVjE5VmdnRUxPRVJ4UldaRGRFaFFMVm1DQVF0eVkxTmxWeTFrUlVGdFdZSUJDMFZpZDFsNE5XZDBXVzl2Z2dFTFpXVktYME5aY1ZOdlZEU0NBUXRPU1VGT1NGVTRaRGx0TklJQkMzbGZVMU51YTB4NU1qSjNnZ0VMZWxaamFteGtUVEZaVFZtQ0FRdDNNMmRwYjJ4RGJUUm1TWUlCQzNGalREaHRaVGhEWVdnd3NnRUdDZ1FJR1JBQzZnRUVDQUlRTUElM0QlM0QYgeDoGCILc2VhcmNoLWZlZWQ%3D",
};
export let targetExercisesData = [
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/Xr8tP7YwMvmdpo",
    id: "0001",
    name: "3/4 sit-up",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Place your hands behind your head with your elbows pointing outwards.",
      "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/OjHQVCtdNtIoK4",
    id: "0002",
    name: "45° side bend",
    target: "abs",
    secondaryMuscles: ["obliques"],
    instructions: [
      "Stand with your feet shoulder-width apart and your arms extended straight down by your sides.",
      "Keeping your back straight and your core engaged, slowly bend your torso to one side, lowering your hand towards your knee.",
      "Pause for a moment at the bottom, then slowly return to the starting position.",
      "Repeat on the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/NkEN3iBq57QEAH",
    id: "0003",
    name: "air bike",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Lie flat on your back with your hands placed behind your head.",
      "Lift your legs off the ground and bend your knees at a 90-degree angle.",
      "Bring your right elbow towards your left knee while simultaneously straightening your right leg.",
      "Return to the starting position and repeat the movement on the opposite side, bringing your left elbow towards your right knee while straightening your left leg.",
      "Continue alternating sides in a pedaling motion for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/c6OjuhttKwe9vG",
    id: "0006",
    name: "alternate heel touchers",
    target: "abs",
    secondaryMuscles: ["obliques"],
    instructions: [
      "Lie flat on your back with your knees bent and feet flat on the ground.",
      "Extend your arms straight out to the sides, parallel to the ground.",
      "Engaging your abs, lift your shoulders off the ground and reach your right hand towards your right heel.",
      "Return to the starting position and repeat on the left side, reaching your left hand towards your left heel.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/X5CAfRlxHhEa0L",
    id: "0010",
    name: "assisted hanging knee raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "lower back"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core and lift your knees towards your chest, keeping your legs together.",
      "Once your knees are at chest level, explosively throw your legs down towards the ground, extending them fully.",
      "Allow your legs to swing back up and repeat the movement for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/rzddalbSEd-13b",
    id: "0011",
    name: "assisted hanging knee raise",
    target: "abs",
    secondaryMuscles: ["hip flexors"],
    instructions: [
      "Hang from a pull-up bar with your arms fully extended and your palms facing away from you.",
      "Engage your core muscles and lift your knees towards your chest, bending at the hips and knees.",
      "Pause for a moment at the top of the movement, squeezing your abs.",
      "Slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/jFuit4M-mzpHBP",
    id: "0012",
    name: "assisted lying leg raise with lateral throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "obliques"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your abs and lift your legs off the ground, keeping them straight.",
      "While keeping your legs together, lower them to one side until they are a few inches above the ground.",
      "Pause for a moment, then lift your legs back to the starting position.",
      "Repeat the movement to the other side.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/7m1aIfwRDosUNR",
    id: "0013",
    name: "assisted lying leg raise with throw down",
    target: "abs",
    secondaryMuscles: ["hip flexors", "quadriceps"],
    instructions: [
      "Lie flat on your back with your legs extended and your arms by your sides.",
      "Place your hands under your glutes for support.",
      "Engage your core and lift your legs off the ground, keeping them straight.",
      "Raise your legs until they are perpendicular to the ground.",
      "Lower your legs back down to the starting position.",
      "Simultaneously, throw your legs down towards the ground, keeping them straight.",
      "Raise your legs back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "medicine ball",
    gifUrl: "https://v2.exercisedb.io/image/AerQygC-icgIbQ",
    id: "0014",
    name: "assisted motion russian twist",
    target: "abs",
    secondaryMuscles: ["obliques", "lower back"],
    instructions: [
      "Sit on the ground with your knees bent and feet flat on the floor.",
      "Hold the medicine ball with both hands in front of your chest.",
      "Lean back slightly, engaging your abs and keeping your back straight.",
      "Slowly twist your torso to the right, bringing the medicine ball towards the right side of your body.",
      "Pause for a moment, then twist your torso to the left, bringing the medicine ball towards the left side of your body.",
      "Continue alternating sides for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "waist",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/qqnMNISvR-TGMF",
    id: "0071",
    name: "barbell press sit-up",
    target: "abs",
    secondaryMuscles: ["shoulders", "chest"],
    instructions: [
      "Lie flat on your back on a mat with your knees bent and feet flat on the ground.",
      "Hold the barbell with an overhand grip, resting it on your chest.",
      "Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
];
export let equipmentExercisesData = [
  {
    bodyPart: "back",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/3VNG7h2H-obbpx",
    id: "0022",
    name: "barbell pullover to press",
    target: "lats",
    secondaryMuscles: ["triceps", "chest", "shoulders"],
    instructions: [
      "Lie flat on a bench with your head at one end and your feet on the ground.",
      "Hold the barbell with a pronated grip (palms facing away from you) and extend your arms straight above your chest.",
      "Keeping your arms straight, lower the barbell behind your head in an arc-like motion until you feel a stretch in your lats.",
      "Pause for a moment, then reverse the motion and press the barbell back to the starting position above your chest.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/IdfhKvMiy-OC-S",
    id: "0023",
    name: "barbell alternate biceps curl",
    target: "biceps",
    secondaryMuscles: ["forearms"],
    instructions: [
      "Stand up straight with your feet shoulder-width apart and hold a barbell in each hand, palms facing forward.",
      "Keep your upper arms stationary and exhale as you curl the weights while contracting your biceps.",
      "Continue to raise the barbells until your biceps are fully contracted and the barbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale as you slowly begin to lower the barbells back to the starting position.",
      "Repeat for the desired number of repetitions, alternating arms.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/Cbq7uqyld7oGmE",
    id: "0024",
    name: "barbell bench front squat",
    target: "quads",
    secondaryMuscles: ["hamstrings", "glutes", "calves"],
    instructions: [
      "Start by standing with your feet shoulder-width apart and the barbell resting on your upper chest, just below your collarbone.",
      "Hold the barbell with an overhand grip, keeping your elbows up and your upper arms parallel to the ground.",
      "Lower your body down into a squat position by bending at the knees and hips, keeping your back straight and your chest up.",
      "Pause for a moment at the bottom of the squat, then push through your heels to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/3CxmMvC6JMRuq4",
    id: "0025",
    name: "barbell bench press",
    target: "pectorals",
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
      "Grasp the barbell with an overhand grip slightly wider than shoulder-width apart.",
      "Lift the barbell off the rack and hold it directly above your chest with your arms fully extended.",
      "Lower the barbell slowly towards your chest, keeping your elbows tucked in.",
      "Pause for a moment when the barbell touches your chest.",
      "Push the barbell back up to the starting position by extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/2HVuWh3zNde0IY",
    id: "0026",
    name: "barbell bench squat",
    target: "quads",
    secondaryMuscles: ["glutes", "hamstrings", "calves"],
    instructions: [
      "Set up a barbell on a squat rack at chest height.",
      "Stand facing away from the rack, with your feet shoulder-width apart.",
      "Bend your knees and lower your body down into a squat position, keeping your back straight and chest up.",
      "Grasp the barbell with an overhand grip, slightly wider than shoulder-width apart.",
      "Lift the barbell off the rack and step back, ensuring your feet are still shoulder-width apart.",
      "Lower your body down into a squat, keeping your knees in line with your toes.",
      "Pause for a moment at the bottom, then push through your heels to return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "back",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/mlVImE5ee5znoC",
    id: "0027",
    name: "barbell bent over row",
    target: "upper back",
    secondaryMuscles: ["biceps", "forearms"],
    instructions: [
      "Stand with your feet shoulder-width apart and knees slightly bent.",
      "Bend forward at the hips while keeping your back straight and chest up.",
      "Grasp the barbell with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Pull the barbell towards your lower chest by retracting your shoulder blades and squeezing your back muscles.",
      "Pause for a moment at the top, then slowly lower the barbell back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/QLXhAfg6c43xNT",
    id: "0028",
    name: "barbell clean and press",
    target: "quads",
    secondaryMuscles: ["hamstrings", "glutes", "shoulders", "triceps"],
    instructions: [
      "Stand with your feet shoulder-width apart and the barbell on the floor in front of you.",
      "Bend your knees and hinge at the hips to lower down and grip the barbell with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Drive through your heels and extend your hips and knees to lift the barbell off the floor, keeping it close to your body.",
      "As the barbell reaches your thighs, explosively extend your hips, shrug your shoulders, and pull the barbell up towards your chest.",
      "As the barbell reaches chest height, quickly drop under it and catch it at shoulder level, with your elbows pointing forward and your palms facing up.",
      "From the catch position, press the barbell overhead by extending your arms and pushing the barbell straight up.",
      "Lower the barbell back down to the starting position and repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper legs",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/0Y89aHbaUx0jLs",
    id: "0029",
    name: "barbell clean-grip front squat",
    target: "glutes",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves", "core"],
    instructions: [
      "Start by standing with your feet shoulder-width apart and the barbell resting on your upper chest, with your elbows pointing forward.",
      "Lower your body by bending your knees and pushing your hips back, as if you are sitting back into a chair.",
      "Keep your chest up and your back straight as you lower down, making sure your knees do not go past your toes.",
      "Continue lowering until your thighs are parallel to the ground, or as low as you can comfortably go.",
      "Pause for a moment at the bottom, then push through your heels to stand back up, extending your hips and knees.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/GHHtMeG-VdqLBz",
    id: "0030",
    name: "barbell close-grip bench press",
    target: "triceps",
    secondaryMuscles: ["chest", "shoulders"],
    instructions: [
      "Lie flat on a bench with your feet flat on the ground and your back pressed against the bench.",
      "Grasp the barbell with a close grip, slightly narrower than shoulder-width apart.",
      "Unrack the barbell and lower it slowly towards your chest, keeping your elbows close to your body.",
      "Pause for a moment when the barbell touches your chest.",
      "Push the barbell back up to the starting position, fully extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/70FzAWguKkDQLq",
    id: "0031",
    name: "barbell curl",
    target: "biceps",
    secondaryMuscles: ["forearms"],
    instructions: [
      "Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, palms facing forward.",
      "Keep your elbows close to your torso and exhale as you curl the weights while contracting your biceps.",
      "Continue to raise the bar until your biceps are fully contracted and the bar is at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale as you slowly begin to lower the bar back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
  },
];
